### ISSUE TITLE
What is RWR format?

### ISSUE THREAD

**Issue by RAbraham** [guitarvydas/arith0d#4]
Hi Paul,
Do you have a writeup for the rwr format and motivations?

**Comment by guitarvydas** [comment]
No spec yet, but, I think that it is easier to guess at the syntax rather than read the spec (when I write one).

I used to call this `glue`, but changed some syntax, like `[[`, `]]`, etc. I probably wrote a `glue` spec (check my blog), but haven't upgraded it to use the newer syntax of `RWR`.

The motivation is: create t2t transpilers only (text-to-text). OhmJS does pattern matching ("parsing"), but then punts to the full generality of Javascript to handle the matches. `RWR` strips away the generality and creates a tiny DSL for doing one specific job, instead of doing anything-and-everything that JS can do - i.e. RWR only rearranges text. This turns out to be wonderfully useful. I don't need the full generality of JS. The simplicity of RWR makes me think more out-of-the-box about interesting things that I can do, instead of worrying about niggly details of getting the JS code right. I use this to parse diagrams. It's "obvious" to me that I could build a whole compiler this way (but, I haven't built an example of this yet). Most people think that a "parser" is some monstrous lump of software that takes months to write, but, I use OhmJS+RWR in a REGEX-y way, taking only minutes to build little parsers. Thinking this way changes my approach to solving big problems and gives me more options.
